# This is a basic workflow to help you get started with Actions

name: Basic Workflow

# Controls when the workflow will run
on:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name:
        description: "Graduate name"
        required: true
        default: "Matt"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  MyFavouriteJob:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      
      - name: Run a one-line script
        run: echo "Hello, ${{github.event.inputs.name}}!"
        
      - name: Run a multi-line script
        run: 
          echo Add other actions to build,
          echo test, and deploy your project.
          
  TheOneThatDoesThings:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Let's see what's in our working directory
        run: ls -a
      - name: Print contents of the eadme
        run: cat README.md
      

    
    
